import {
  Shield, Lock, Cpu, Zap, Clock, AlertTriangle, Users,
  Download, Settings, MessageSquare, Sparkles, Building2,
} from 'lucide-react';
import type { SiteId } from '../sites';
import type { SiteContent } from './types';

export type { SiteContent };

export const content: Record<SiteId, SiteContent> = {
  /* ================================================================
   *  DSGVOCLAW — German / DSGVO framing
   * ================================================================ */
  dsgvoclaw: {
    nav: {
      links: [
        { href: '#problem', label: 'Problem' },
        { href: '#features', label: 'Features' },
        { href: '#how-it-works', label: "So funktioniert's" },
        { href: '#pricing', label: 'Preise' },
        { href: '#social-proof', label: 'Kunden' },
        { href: '#faq', label: 'FAQ' },
        { href: '#docs', label: 'Docs' },
      ],
      signIn: 'Anmelden',
      signUp: 'Registrieren',
    },
    hero: {
      tags: [
        { icon: Shield, label: 'Made in Germany', variant: 'sage' },
        { icon: Lock, label: 'DSGVO-konform', variant: 'terracotta' },
        { icon: Cpu, label: 'Sandboxed AI', variant: 'cream' },
        { icon: Zap, label: 'NVIDIA-Powered', variant: 'cream' },
      ],
      headlineLines: ['Ihr KI-Mitarbeiter,', 'sicher in der Sandbox.'],
      headlineAccent: '100% DSGVO-konform.',
      subheadline:
        'KI-Agenten, die in einer <strong>isolierten Sandbox</strong> arbeiten – mit <strong>52+ Skills</strong> für E-Mails, Kalender, Recherche und mehr. Ihre Daten verlassen <strong>niemals Ihre Server</strong>.',
      urgencyText: 'Sandboxed AI ist die Zukunft der DSGVO-konformen Automatisierung.',
      primaryCta: 'Jetzt starten',
      secondaryCta: 'Preise ansehen',
      stats: [
        { icon: Sparkles, value: '52+', label: 'KI-Skills', variant: 'sage', details: ['E-Mail & Kalender', 'Recherche & Reports', 'Code-Review & Docs'] },
        { icon: MessageSquare, value: '22+', label: 'Kanäle', variant: 'terracotta', details: ['WhatsApp & Telegram', 'Slack & Teams', 'Discord & Signal'] },
        { icon: Clock, value: '24/7', label: 'Verfügbarkeit', variant: 'cream', details: ['Sandbox-geschützt', 'Audit-Log aktiv', 'Null Ausfallzeit'] },
      ],
    },
    problem: {
      sectionLabel: 'Die Herausforderung',
      headline: 'Manuelle Arbeit frisst Ihre',
      headlineAccent: 'Wettbewerbsfähigkeit',
      subheadline: 'Während Ihre Konkurrenz bereits KI einsetzt, verlieren Sie Zeit mit Routineaufgaben',
      withoutLabel: 'Ohne KI-Mitarbeiter:',
      withLabel: 'Mit DSGVOClaw:',
      items: [
        {
          icon: Clock,
          title: 'Zeitverlust',
          metric: '200+',
          subtitle: 'Stunden/Monat',
          description: 'Manuelle E-Mails, Kalender, Reports – Zeit, die für strategische Aufgaben fehlt.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '200+ Stunden pro Monat für Routineaufgaben',
            '67% der Arbeitszeit ist reaktive Verwaltung',
            'Wichtige strategische Projekte werden verschoben',
            'Überstunden und Burnout-Risiko steigt',
          ],
          pros: [
            'Mit KI: Inbox Zero in 10 Minuten statt 2 Stunden',
            'Automatische Report-Erstellung über Nacht',
            'Fokus auf wertschöpfende Aufgaben',
          ],
        },
        {
          icon: AlertTriangle,
          title: 'DSGVO-Risiko',
          metric: '€20 Mio.',
          subtitle: 'Max. Bußgeld',
          description: 'KI-Agenten ohne Sandbox können unkontrolliert Daten übertragen. Ohne DSGVO-Dokumentation drohen existenzbedrohende Strafen.',
          variant: 'rose',
          bgVariant: 'terracotta',
          cons: [
            'KI-Tools ohne Sandbox = unkontrollierter Datenzugriff',
            'Bußgelder bis zu €20 Mio. oder 4% des Umsatzes',
            'Anstieg der Verstöße um 340% in 2023',
            'Meldungsfrist von nur 72 Stunden bei Datenpannen',
            'Schadensersatzforderungen von Kunden',
            'Reputationsverlust und Imageschaden',
          ],
          pros: [
            'Sandboxed: Landlock + seccomp + Netzwerk-Isolation',
            'Automatische Dokumentation aller Prozesse',
            'Prüfungsbereit für jede Behörde',
          ],
        },
        {
          icon: Users,
          title: 'Personalmangel',
          metric: '70%',
          subtitle: 'der KMUs',
          description: 'Haben keine Kapazität für zusätzliche administrative FTEs.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '70% der KMUs haben keinen Datenschutzbeauftragten',
            '€80.000+ Kosten pro zusätzlichem FTE',
            '6+ Monate bis zur vollen Einsatzfähigkeit',
            'Hohe Fluktuation in administrativen Rollen',
            'Schwierig: gute Assistenten zu finden',
          ],
          pros: [
            'Ein KI-Mitarbeiter mit 52+ Skills ersetzt 2–4 FTEs',
            'Sofort einsatzbereit in unter 10 Minuten',
            'Arbeitet 24/7 sicher in der Sandbox',
            'Skalierbar ohne Neueinstellungen',
          ],
        },
      ],
    },
    features: {
      sectionLabel: 'KI-Automatisierung',
      headline: 'Ein KI-Mitarbeiter für',
      headlineAccent: 'alle Ihre Aufgaben',
      subheadline: 'E-Mails, Kalender, Reports, Recherche – vollautomatisch und DSGVO-sicher',
      email: {
        tag: 'Inbox Zero',
        title: 'E-Mail & Kommunikation',
        description: 'KI-Agenten lesen, kategorisieren und beantworten E-Mails automatisch – alles innerhalb der sicheren Sandbox.',
        skillTags: ['himalaya E-Mail Skill', 'Termine koordinieren'],
        checklist: ['Inbox Zero jeden Tag', 'Intelligente Priorisierung', 'Follow-up Erinnerungen', 'Mehrsprachig (DE/EN)'],
      },
      research: {
        tag: 'Research',
        title: 'Recherche & Analyse',
        description: 'Recherchiert Marktdaten, fasst Dokumente zusammen und erstellt professionelle Reports – powered by 52+ OpenClaw Skills.',
        stats: [
          { value: '10x', label: 'schneller' },
          { value: '99%', label: 'Genauigkeit' },
        ],
        skillTags: ['summarize Skill', 'coding-agent Skill', '52+ Skills'],
      },
      sandbox: {
        tag: 'NemoClaw',
        title: 'Sandbox-Sicherheit',
        description: 'Jeder KI-Agent läuft in einer isolierten Sandbox mit Landlock, seccomp und Netzwerk-Isolation. Kein unkontrollierter Zugriff auf Ihre Systeme.',
        checklist: [
          'Netzwerk: Alle Ausgangsverbindungen blockiert',
          'Dateisystem: Zugriff nur auf /sandbox und /tmp',
          'Prozesse: Privilege Escalation verhindert',
          'Inferenz: Nur genehmigte KI-Modelle erlaubt',
        ],
      },
      compliance: {
        tag: 'DSGVO',
        title: 'Automatische Compliance',
        description: 'Automatische DSGVO-Dokumentation, Audit-Logs und Compliance-Überwachung – ohne Ihr Zutun.',
        checklist: [
          'Verzeichnis der Verarbeitungstätigkeiten',
          'DSFA automatisch generiert',
          'Vollständiges Audit-Log',
          'Rechtskonforme Dokumente',
        ],
      },
      integrations: {
        sectionLabel: 'Integrationen',
        title: 'Verbindung mit Ihren Tools',
        subtitle: 'Nahtlose Integration in Ihre bestehende Infrastruktur. Der KI-Mitarbeiter arbeitet direkt mit den Tools, die Sie täglich nutzen.',
        categories: {
          communication: 'Kommunikationskanäle',
          productivity: 'Produktivität & Dokumente',
          infrastructure: 'KI & Infrastruktur',
        },
      },
    },
    howItWorks: {
      sectionLabel: "So funktioniert's",
      headline: 'Ihr KI-Mitarbeiter in',
      headlineAccent: 'unter 10 Minuten einsatzbereit',
      subheadline: 'Von der Installation bis zum ersten Ergebnis – vier Schritte zu Ihrem sicheren KI-Assistenten',
      steps: [
        {
          number: '01',
          icon: Download,
          title: 'MasterCrab installieren',
          description: 'Ein Befehl genügt. MasterCrab installiert automatisch NemoClaw, OpenClaw und alle Abhängigkeiten auf Ihrem Server. Docker, Sandbox und Sicherheitsrichtlinien werden konfiguriert.',
          variant: 'sage',
          bullets: [
            'Ein-Befehl-Installation: curl -fsSL install.mastercrab.de | bash',
            'Automatische Docker- und Sandbox-Konfiguration',
            'DSGVO-konforme Standardeinstellungen ab Werk',
          ],
          features: ['Ubuntu 22.04+', 'Docker inkl.', 'Keine GPU nötig'],
          time: '< 10 Min.',
        },
        {
          number: '02',
          icon: Settings,
          title: 'Sandbox konfigurieren',
          description: 'Über das lokale Admin-Panel (localhost) konfigurieren Sie Netzwerkrichtlinien, erlaubte Hosts und KI-Modelle. Alles YAML-basiert und jederzeit anpassbar.',
          variant: 'terracotta',
          bullets: [
            'Admin-Panel: Übersichtliche Web-Oberfläche auf localhost',
            'Netzwerk-Policies: Erlaubte Domains per YAML definieren',
            'KI-Modelle: NVIDIA Nemotron, Ollama oder eigene Modelle',
          ],
          features: ['YAML-Konfiguration', 'Hot-Reload', 'Audit-Logging'],
          time: '< 5 Min.',
        },
        {
          number: '03',
          icon: MessageSquare,
          title: 'Kanäle verbinden',
          description: 'Verbinden Sie Ihre Kommunikationskanäle: WhatsApp, Telegram, Slack, Teams, Discord und mehr. Ihre Teams kommunizieren direkt mit dem KI-Mitarbeiter.',
          variant: 'cream',
          bullets: [
            '22+ Kanäle: WhatsApp, Telegram, Slack, Teams, Discord, Signal',
            'Per-Kanal Allowlists: Nur autorisierte Nutzer haben Zugriff',
            'Gruppen-Gating: In Gruppenchats nur per @mention aktiviert',
          ],
          features: ['22+ Kanäle', 'Allowlists', 'Verschlüsselt'],
          time: '< 10 Min.',
        },
        {
          number: '04',
          icon: Sparkles,
          title: 'KI arbeitet in der Sandbox',
          description: 'Ab sofort arbeitet Ihr KI-Mitarbeiter rund um die Uhr – sicher eingesperrt in der NemoClaw-Sandbox. 52+ Skills für E-Mails, Recherche, Reports und mehr.',
          variant: 'sage',
          bullets: [
            'Sandboxed: Landlock + seccomp + Netzwerk-Isolation aktiv',
            '52+ Skills: E-Mail, Kalender, Recherche, Coding, Dokumente',
            'Vollständiges Audit-Log: Jede Aktion wird protokolliert',
          ],
          features: ['24/7 Verfügbarkeit', 'DSGVO-Compliance', 'Audit-Logs'],
          time: '24/7',
        },
      ],
      ctaText: 'Jetzt starten',
    },
    pricing: {
      sectionLabel: 'Preise',
      headline: 'Einfache, transparente',
      headlineAccent: 'Preise',
      subheadline: 'Monatliche Subscription – jederzeit kündbar',
      annualNote: 'Jahreszahlung: 2 Monate geschenkt – jederzeit kündbar',
      plans: [
        {
          title: 'Starter',
          icon: Shield,
          price: '€149',
          priceNote: '/Monat',
          description: 'Für kleine Teams, die mit sicherer KI starten möchten',
          features: [
            '1 Sandboxed KI-Agent',
            'Kern-Skills: E-Mail, Kalender, Recherche',
            '3 Kommunikationskanäle',
            'Lokale Sandbox (Landlock + seccomp)',
            'DSGVO-Dokumentation automatisch',
            'Admin-Panel (localhost)',
            'E-Mail Support',
            '99.9% Uptime Garantie',
          ],
          ctaText: 'Jetzt kaufen',
          variant: 'default',
          color: 'sage',
        },
        {
          title: 'Professional',
          icon: Sparkles,
          price: '€299',
          priceNote: '/Monat',
          description: 'Voller Funktionsumfang für wachsende Unternehmen',
          features: [
            'Bis zu 5 Sandboxed KI-Agenten',
            'Alle 52+ OpenClaw Skills',
            'Alle 22+ Kommunikationskanäle',
            'NVIDIA Nemotron + Ollama Support',
            'Erweiterte Netzwerk-Policies (YAML)',
            'ClawHub Marketplace Zugang',
            'Prioritäts-Support (< 2h Antwortzeit)',
            'Team-Verwaltung & RBAC',
            'Erweitertes Audit-Dashboard',
            'Managed Updates',
          ],
          ctaText: 'Jetzt kaufen',
          variant: 'highlighted',
          badge: 'Meistgewählt',
          color: 'terracotta',
        },
        {
          title: 'Enterprise',
          icon: Building2,
          price: '€599',
          priceNote: '/Monat',
          description: 'Für Unternehmen mit höchsten Sicherheitsanforderungen',
          features: [
            'Unbegrenzte Sandboxed KI-Agenten',
            'Alle Professional Features',
            'Dedizierter Account Manager',
            'Custom Skills & Integrationen',
            'On-Premise Deployment Support',
            'Premium SLA (99.99% Uptime)',
            'Compliance-Manager & Audit-Report',
            'On-Site Onboarding & Schulung',
          ],
          ctaText: 'Jetzt kaufen',
          variant: 'default',
          color: 'cream',
        },
      ],
      guaranteeText: '30 Tage Geld-zurück-Garantie – risikolos kaufen',
    },
    socialProof: {
      sectionLabel: 'Testimonials',
      headline: 'Was unsere',
      headlineAccent: 'Kunden sagen',
      subheadline: 'Vertrauen von über 200 Unternehmen in Deutschland',
      testimonials: [
        {
          quote: 'DSGVOClaw hat unsere Datenschutzprozesse komplett automatisiert. Der KI-Agent bearbeitet unsere Mandanten-E-Mails und erstellt Audit-Reports – alles in der Sandbox, kein Datenleck möglich.',
          author: 'Dr. Katrin Berger',
          role: 'Datenschutzbeauftragte',
          company: 'kbht Wirtschaftsprüfer GmbH',
          rating: 5,
          variant: 'sage',
        },
        {
          quote: 'Die Sandbox-Technologie war für uns der entscheidende Faktor. Unsere Kanzlei verarbeitet hochsensible Mandantendaten – mit DSGVOClaw können wir KI nutzen, ohne Kompromisse bei der Sicherheit.',
          author: 'Stefan Hartmann',
          role: 'Managing Partner',
          company: 'PSP Peters Schönberger & Partner',
          rating: 5,
          variant: 'terracotta',
        },
        {
          quote: 'Wir haben 3 administrative Stellen durch den KI-Mitarbeiter ergänzt. E-Mail-Triage, Terminkoordination und Recherche laufen jetzt automatisch – mit 52+ Skills, die wir nach Bedarf aktivieren.',
          author: 'Lena Richter',
          role: 'Geschäftsführerin',
          company: 'Ypsilon GmbH',
          rating: 5,
          variant: 'cream',
        },
      ],
    },
    faq: {
      sectionLabel: 'FAQ',
      headline: 'Häufig gestellte',
      headlineAccent: 'Fragen',
      subheadline: 'Alles, was Sie über DSGVOClaw wissen müssen',
      items: [
        {
          question: 'Was kann der KI-Mitarbeiter konkret tun?',
          answer: 'Ihr KI-Mitarbeiter verfügt über 52+ Skills: E-Mails lesen und beantworten, Kalender verwalten, Recherchen durchführen, Reports und Präsentationen erstellen, Code schreiben und reviewen, Dokumente zusammenfassen, sowie DSGVO-Dokumentation automatisch pflegen. Er arbeitet 24/7 innerhalb einer sicheren Sandbox.',
        },
        {
          question: 'Was bedeutet "Sandboxed Execution"?',
          answer: 'Jeder KI-Agent läuft in einer isolierten Sandbox, geschützt durch drei Sicherheitsschichten: Landlock (Dateisystem-Isolation – nur /sandbox und /tmp zugänglich), seccomp (blockiert gefährliche Systemaufrufe), und Netzwerk-Namespaces (alle ausgehenden Verbindungen standardmäßig blockiert). Unbekannte Hosts müssen vom Administrator genehmigt werden.',
        },
        {
          question: 'Brauche ich eine GPU oder spezielle Hardware?',
          answer: 'Nein. Die KI-Inferenz läuft über NVIDIA Nemotron 3 Super (120B) in der Cloud – Sie brauchen keine lokale GPU. Für die Sandbox benötigen Sie nur einen Linux-Server mit Docker: mindestens 4 vCPUs, 8 GB RAM (16 GB empfohlen), und 20-40 GB Festplatte. Alternativ können Sie lokale Modelle via Ollama nutzen.',
        },
        {
          question: 'Sind meine Daten wirklich sicher?',
          answer: 'Absolut. Ihre Daten verlassen niemals Ihre Server. Der KI-Agent läuft in einer NemoClaw-Sandbox mit vollständiger Netzwerk-Isolation. Nur explizit genehmigte Verbindungen sind erlaubt. Alle Aktionen werden in einem DSGVO-konformen Audit-Log protokolliert (90 Tage Aufbewahrung). Sessions werden nach 30 Tagen automatisch gelöscht.',
        },
        {
          question: 'Welche Kommunikationskanäle werden unterstützt?',
          answer: 'Über 22 Kanäle: WhatsApp, Telegram, Slack, Microsoft Teams, Discord, Signal, iMessage, Matrix, IRC, Google Chat, WebChat und mehr. Jeder Kanal hat eigene Allowlists – nur autorisierte Nutzer können mit dem KI-Mitarbeiter interagieren. In Gruppenchats wird der Agent nur per @mention aktiviert.',
        },
        {
          question: 'Wie unterscheidet sich das von ChatGPT oder anderen KI-Tools?',
          answer: 'ChatGPT und US-basierte Tools übertragen Ihre Daten in unsichere Drittländer – ein massives DSGVO-Risiko. DSGVOClaw läuft vollständig auf Ihren Servern in einer Sandbox. Kein Datentransfer in die USA, keine Nutzung für KI-Training, vollständige Kontrolle. Außerdem ist unser KI-Mitarbeiter kein Chatbot, sondern ein autonomer Agent mit 52+ Skills.',
        },
        {
          question: 'Wie lange dauert die Einrichtung?',
          answer: 'Unter 10 Minuten. Ein Befehl installiert MasterCrab (unseren NemoClaw-Wrapper) mit allen Abhängigkeiten. Danach konfigurieren Sie über das lokale Admin-Panel Ihre Netzwerk-Policies und verbinden Ihre Kanäle. Der KI-Mitarbeiter beginnt sofort zu arbeiten.',
        },
      ],
      contactTitle: 'Noch Fragen?',
      contactSubtitle: 'Unser Team hilft Ihnen gerne weiter',
      contactCta: 'Kontakt aufnehmen',
    },
    cta: {
      badge: 'Jetzt beitreten',
      headline: 'Starten Sie 2026 mit einem',
      headlineAccent: 'KI-Vorsprung',
      subheadline: 'Starten Sie jetzt mit Ihrem KI-Mitarbeiter – voller Funktionsumfang, DSGVO-konform, sofort einsatzbereit auf Ihren Servern.',
      emailPlaceholder: 'Ihre E-Mail-Adresse',
      submitText: 'Beitreten',
      benefits: ['Sofort einsatzbereit', 'Jederzeit kündbar', 'DSGVO-konform'],
      trustBadges: ['DSGVO-konform', 'Setup in 10 Min.', '200+ Unternehmen'],
      urgencyText: '2026 wird das Jahr, in dem KI zum Standard wird. Die Frage ist nicht mehr „ob", sondern „wann".',
    },
    footer: {
      description: 'Der sichere KI-Mitarbeiter für deutsche Unternehmen. Sandboxed AI powered by NemoClaw – Self-hosted, DSGVO-konform, keine Kompromisse.',
      columns: [
        {
          title: 'Produkt',
          links: [
            { label: 'Features', href: '#features' },
            { label: 'Preise', href: '#pricing' },
            { label: 'FAQ', href: '#faq' },
            { label: 'MasterCrab Docs', href: '#docs' },
          ],
        },
        {
          title: 'Unternehmen',
          links: [
            { label: 'Über uns', href: '#' },
            { label: 'Blog', href: '#' },
            { label: 'Karriere', href: '#' },
            { label: 'Kontakt', href: '#' },
          ],
        },
        {
          title: 'Rechtliches',
          links: [
            { label: 'Impressum', href: '#' },
            { label: 'Datenschutz', href: '#' },
            { label: 'AGB', href: '#' },
            { label: 'Cookie-Richtlinie', href: '#' },
          ],
        },
        {
          title: 'Open Source',
          links: [
            { label: 'MasterCrab (GitHub)', href: 'https://github.com/dsgvoclaw/mastercrab' },
            { label: 'OpenClaw', href: 'https://github.com/openclaw/openclaw' },
            { label: 'NemoClaw', href: 'https://github.com/nvidia/nemoclaw' },
            { label: 'ClawHub Marketplace', href: 'https://clawhub.ai' },
          ],
        },
      ],
      copyright: '© 2026 DSGVOClaw. Alle Rechte vorbehalten.',
      madeIn: 'Made in Germany',
      lovesLabel: 'Datenschutz',
    },
  },

  /* ================================================================
   *  GDPRCLAW — English / GDPR framing
   * ================================================================ */
  gdprclaw: {
    nav: {
      links: [
        { href: '#problem', label: 'Problem' },
        { href: '#features', label: 'Features' },
        { href: '#how-it-works', label: 'How It Works' },
        { href: '#pricing', label: 'Pricing' },
        { href: '#social-proof', label: 'Customers' },
        { href: '#faq', label: 'FAQ' },
        { href: '#docs', label: 'Docs' },
      ],
      signIn: 'Sign In',
      signUp: 'Sign Up',
    },
    hero: {
      tags: [
        { icon: Shield, label: 'Made in the EU', variant: 'sage' },
        { icon: Lock, label: 'GDPR-Compliant', variant: 'terracotta' },
        { icon: Cpu, label: 'Sandboxed AI', variant: 'cream' },
        { icon: Zap, label: 'NVIDIA-Powered', variant: 'cream' },
      ],
      headlineLines: ['Your AI Employee,', 'secure in the Sandbox.'],
      headlineAccent: '100% GDPR-Compliant.',
      subheadline:
        'AI agents that work inside an <strong>isolated sandbox</strong> – with <strong>52+ skills</strong> for emails, calendar, research and more. Your data <strong>never leaves your servers</strong>.',
      urgencyText: 'Sandboxed AI is the future of GDPR-compliant automation.',
      primaryCta: 'Get Started',
      secondaryCta: 'View Pricing',
      stats: [
        { icon: Sparkles, value: '52+', label: 'AI Skills', variant: 'sage', details: ['Email & Calendar', 'Research & Reports', 'Code Review & Docs'] },
        { icon: MessageSquare, value: '22+', label: 'Channels', variant: 'terracotta', details: ['WhatsApp & Telegram', 'Slack & Teams', 'Discord & Signal'] },
        { icon: Clock, value: '24/7', label: 'Availability', variant: 'cream', details: ['Sandbox-protected', 'Audit log active', 'Zero downtime'] },
      ],
    },
    problem: {
      sectionLabel: 'The Challenge',
      headline: 'Manual work is eating your',
      headlineAccent: 'Competitiveness',
      subheadline: 'While your competitors already use AI, you\'re losing time on routine tasks',
      withoutLabel: 'Without AI Employee:',
      withLabel: 'With GDPRClaw:',
      items: [
        {
          icon: Clock,
          title: 'Time Lost',
          metric: '200+',
          subtitle: 'Hours/Month',
          description: 'Manual emails, calendar, reports – time missing for strategic work.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '200+ hours per month on routine tasks',
            '67% of work time is reactive administration',
            'Critical strategic projects get postponed',
            'Overtime and burnout risk increases',
          ],
          pros: [
            'With AI: Inbox Zero in 10 minutes instead of 2 hours',
            'Automatic report generation overnight',
            'Focus on value-creating tasks',
          ],
        },
        {
          icon: AlertTriangle,
          title: 'GDPR Risk',
          metric: '€20M',
          subtitle: 'Max. Fine',
          description: 'AI agents without a sandbox can transfer data uncontrollably. Without GDPR documentation, devastating fines await.',
          variant: 'rose',
          bgVariant: 'terracotta',
          cons: [
            'AI tools without sandbox = uncontrolled data access',
            'Fines up to €20M or 4% of annual revenue',
            '340% increase in violations in 2023',
            'Only 72-hour reporting window for data breaches',
            'Compensation claims from customers',
            'Reputation loss and brand damage',
          ],
          pros: [
            'Sandboxed: Landlock + seccomp + network isolation',
            'Automatic documentation of all processes',
            'Audit-ready for any authority',
          ],
        },
        {
          icon: Users,
          title: 'Talent Shortage',
          metric: '70%',
          subtitle: 'of SMEs',
          description: 'Have no capacity for additional administrative FTEs.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '70% of SMEs have no Data Protection Officer',
            '€80,000+ cost per additional FTE',
            '6+ months until fully operational',
            'High turnover in administrative roles',
            'Difficult to find qualified assistants',
          ],
          pros: [
            'One AI employee with 52+ skills replaces 2–4 FTEs',
            'Ready to work in under 10 minutes',
            'Works 24/7 securely in the sandbox',
            'Scalable without new hires',
          ],
        },
      ],
    },
    features: {
      sectionLabel: 'AI Automation',
      headline: 'One AI employee for',
      headlineAccent: 'all your tasks',
      subheadline: 'Emails, calendar, reports, research – fully automated and GDPR-secure',
      email: {
        tag: 'Inbox Zero',
        title: 'Email & Communication',
        description: 'AI agents read, categorize and respond to emails automatically – all within the secure sandbox.',
        skillTags: ['himalaya Email Skill', 'Schedule Meetings'],
        checklist: ['Inbox Zero every day', 'Intelligent prioritization', 'Follow-up reminders', 'Multilingual (EN/DE)'],
      },
      research: {
        tag: 'Research',
        title: 'Research & Analysis',
        description: 'Researches market data, summarizes documents and creates professional reports – powered by 52+ OpenClaw Skills.',
        stats: [
          { value: '10x', label: 'faster' },
          { value: '99%', label: 'accuracy' },
        ],
        skillTags: ['summarize Skill', 'coding-agent Skill', '52+ Skills'],
      },
      sandbox: {
        tag: 'NemoClaw',
        title: 'Sandbox Security',
        description: 'Every AI agent runs in an isolated sandbox with Landlock, seccomp and network isolation. No uncontrolled access to your systems.',
        checklist: [
          'Network: All outbound connections blocked',
          'Filesystem: Access only to /sandbox and /tmp',
          'Processes: Privilege escalation prevented',
          'Inference: Only approved AI models allowed',
        ],
      },
      compliance: {
        tag: 'GDPR',
        title: 'Automatic Compliance',
        description: 'Automatic GDPR documentation, audit logs and compliance monitoring – without your intervention.',
        checklist: [
          'Record of Processing Activities',
          'DPIA automatically generated',
          'Complete audit log',
          'Legally compliant documents',
        ],
      },
      integrations: {
        sectionLabel: 'Integrations',
        title: 'Connect with Your Tools',
        subtitle: 'Seamless integration into your existing infrastructure. The AI employee works directly with the tools you use every day.',
        categories: {
          communication: 'Communication Channels',
          productivity: 'Productivity & Documents',
          infrastructure: 'AI & Infrastructure',
        },
      },
    },
    howItWorks: {
      sectionLabel: 'How It Works',
      headline: 'Your AI employee',
      headlineAccent: 'ready in under 10 minutes',
      subheadline: 'From installation to first result – four steps to your secure AI assistant',
      steps: [
        {
          number: '01',
          icon: Download,
          title: 'Install MasterCrab',
          description: 'One command is all it takes. MasterCrab automatically installs NemoClaw, OpenClaw and all dependencies on your server. Docker, sandbox and security policies are configured.',
          variant: 'sage',
          bullets: [
            'One-command install: curl -fsSL install.mastercrab.eu | bash',
            'Automatic Docker and sandbox configuration',
            'GDPR-compliant defaults out of the box',
          ],
          features: ['Ubuntu 22.04+', 'Docker incl.', 'No GPU needed'],
          time: '< 10 min',
        },
        {
          number: '02',
          icon: Settings,
          title: 'Configure Sandbox',
          description: 'Use the local admin panel (localhost) to configure network policies, allowed hosts and AI models. Everything is YAML-based and adjustable at any time.',
          variant: 'terracotta',
          bullets: [
            'Admin Panel: Clean web interface on localhost',
            'Network Policies: Define allowed domains via YAML',
            'AI Models: NVIDIA Nemotron, Ollama or custom models',
          ],
          features: ['YAML Config', 'Hot-Reload', 'Audit Logging'],
          time: '< 5 min',
        },
        {
          number: '03',
          icon: MessageSquare,
          title: 'Connect Channels',
          description: 'Connect your communication channels: WhatsApp, Telegram, Slack, Teams, Discord and more. Your teams communicate directly with the AI employee.',
          variant: 'cream',
          bullets: [
            '22+ channels: WhatsApp, Telegram, Slack, Teams, Discord, Signal',
            'Per-channel allowlists: Only authorized users have access',
            'Group gating: Activated only via @mention in group chats',
          ],
          features: ['22+ Channels', 'Allowlists', 'Encrypted'],
          time: '< 10 min',
        },
        {
          number: '04',
          icon: Sparkles,
          title: 'AI Works in the Sandbox',
          description: 'From now on your AI employee works around the clock – securely contained in the NemoClaw sandbox. 52+ skills for emails, research, reports and more.',
          variant: 'sage',
          bullets: [
            'Sandboxed: Landlock + seccomp + network isolation active',
            '52+ Skills: Email, calendar, research, coding, documents',
            'Complete audit log: Every action is logged',
          ],
          features: ['24/7 Availability', 'GDPR Compliance', 'Audit Logs'],
          time: '24/7',
        },
      ],
      ctaText: 'Get Started',
    },
    pricing: {
      sectionLabel: 'Pricing',
      headline: 'Simple, transparent',
      headlineAccent: 'Pricing',
      subheadline: 'Monthly subscription – cancel anytime',
      annualNote: 'Annual billing: 2 months free – cancel anytime',
      plans: [
        {
          title: 'Starter',
          icon: Shield,
          price: '€149',
          priceNote: '/month',
          description: 'For small teams starting with secure AI',
          features: [
            '1 Sandboxed AI Agent',
            'Core Skills: Email, Calendar, Research',
            '3 Communication Channels',
            'Local Sandbox (Landlock + seccomp)',
            'GDPR Documentation automatic',
            'Admin Panel (localhost)',
            'Email Support',
            '99.9% Uptime Guarantee',
          ],
          ctaText: 'Buy Now',
          variant: 'default',
          color: 'sage',
        },
        {
          title: 'Professional',
          icon: Sparkles,
          price: '€299',
          priceNote: '/month',
          description: 'Full functionality for growing businesses',
          features: [
            'Up to 5 Sandboxed AI Agents',
            'All 52+ OpenClaw Skills',
            'All 22+ Communication Channels',
            'NVIDIA Nemotron + Ollama Support',
            'Advanced Network Policies (YAML)',
            'ClawHub Marketplace Access',
            'Priority Support (< 2h response)',
            'Team Management & RBAC',
            'Advanced Audit Dashboard',
            'Managed Updates',
          ],
          ctaText: 'Buy Now',
          variant: 'highlighted',
          badge: 'Most Popular',
          color: 'terracotta',
        },
        {
          title: 'Enterprise',
          icon: Building2,
          price: '€599',
          priceNote: '/month',
          description: 'For organizations with highest security requirements',
          features: [
            'Unlimited Sandboxed AI Agents',
            'All Professional Features',
            'Dedicated Account Manager',
            'Custom Skills & Integrations',
            'On-Premise Deployment Support',
            'Premium SLA (99.99% Uptime)',
            'Compliance Manager & Audit Report',
            'On-Site Onboarding & Training',
          ],
          ctaText: 'Buy Now',
          variant: 'default',
          color: 'cream',
        },
      ],
      guaranteeText: '30-day money-back guarantee – risk-free purchase',
    },
    socialProof: {
      sectionLabel: 'Testimonials',
      headline: 'What our',
      headlineAccent: 'customers say',
      subheadline: 'Trusted by over 200 companies across Europe',
      testimonials: [
        {
          quote: 'GDPRClaw completely automated our data protection processes. The AI agent handles our client emails and creates audit reports – all in the sandbox, no data leaks possible.',
          author: 'Dr. Katrin Berger',
          role: 'Data Protection Officer',
          company: 'kbht Auditors GmbH',
          rating: 5,
          variant: 'sage',
        },
        {
          quote: 'The sandbox technology was the decisive factor for us. Our firm processes highly sensitive client data – with GDPRClaw we can use AI without compromising security.',
          author: 'Stefan Hartmann',
          role: 'Managing Partner',
          company: 'PSP Peters Schönberger & Partner',
          rating: 5,
          variant: 'terracotta',
        },
        {
          quote: 'We augmented 3 administrative positions with the AI employee. Email triage, scheduling and research now run automatically – with 52+ skills we activate as needed.',
          author: 'Lena Richter',
          role: 'Managing Director',
          company: 'Ypsilon GmbH',
          rating: 5,
          variant: 'cream',
        },
      ],
    },
    faq: {
      sectionLabel: 'FAQ',
      headline: 'Frequently Asked',
      headlineAccent: 'Questions',
      subheadline: 'Everything you need to know about GDPRClaw',
      items: [
        {
          question: 'What can the AI employee actually do?',
          answer: 'Your AI employee has 52+ skills: read and respond to emails, manage calendars, conduct research, create reports and presentations, write and review code, summarize documents, and automatically maintain GDPR documentation. It works 24/7 within a secure sandbox.',
        },
        {
          question: 'What does "Sandboxed Execution" mean?',
          answer: 'Every AI agent runs in an isolated sandbox, protected by three security layers: Landlock (filesystem isolation – only /sandbox and /tmp accessible), seccomp (blocks dangerous system calls), and network namespaces (all outbound connections blocked by default). Unknown hosts must be approved by the administrator.',
        },
        {
          question: 'Do I need a GPU or special hardware?',
          answer: 'No. AI inference runs via NVIDIA Nemotron 3 Super (120B) in the cloud – you don\'t need a local GPU. For the sandbox you only need a Linux server with Docker: minimum 4 vCPUs, 8 GB RAM (16 GB recommended), and 20-40 GB disk. Alternatively, you can use local models via Ollama.',
        },
        {
          question: 'Is my data really secure?',
          answer: 'Absolutely. Your data never leaves your servers. The AI agent runs in a NemoClaw sandbox with complete network isolation. Only explicitly approved connections are allowed. All actions are logged in a GDPR-compliant audit log (90-day retention). Sessions are automatically deleted after 30 days.',
        },
        {
          question: 'Which communication channels are supported?',
          answer: 'Over 22 channels: WhatsApp, Telegram, Slack, Microsoft Teams, Discord, Signal, iMessage, Matrix, IRC, Google Chat, WebChat and more. Each channel has its own allowlists – only authorized users can interact with the AI employee. In group chats, the agent is only activated via @mention.',
        },
        {
          question: 'How is this different from ChatGPT or other AI tools?',
          answer: 'ChatGPT and US-based tools transfer your data to insecure third countries – a massive GDPR risk. GDPRClaw runs entirely on your servers in a sandbox. No data transfer to the US, no use for AI training, complete control. Plus, our AI employee is not a chatbot, but an autonomous agent with 52+ skills.',
        },
        {
          question: 'How long does setup take?',
          answer: 'Under 10 minutes. One command installs MasterCrab (our NemoClaw wrapper) with all dependencies. Then configure your network policies via the local admin panel and connect your channels. The AI employee starts working immediately.',
        },
      ],
      contactTitle: 'Still have questions?',
      contactSubtitle: 'Our team is happy to help',
      contactCta: 'Contact Us',
    },
    cta: {
      badge: 'Join Now',
      headline: 'Start 2026 with an',
      headlineAccent: 'AI Advantage',
      subheadline: 'Get started with your AI employee now – full functionality, GDPR-compliant, instantly ready on your servers.',
      emailPlaceholder: 'Your email address',
      submitText: 'Join',
      benefits: ['Ready instantly', 'Cancel anytime', 'GDPR-compliant'],
      trustBadges: ['GDPR-Compliant', 'Setup in 10 min', '200+ Companies'],
      urgencyText: '2026 will be the year AI becomes standard. The question is no longer "if" but "when".',
    },
    footer: {
      description: 'The secure AI employee for European businesses. Sandboxed AI powered by NemoClaw – self-hosted, GDPR-compliant, no compromises.',
      columns: [
        {
          title: 'Product',
          links: [
            { label: 'Features', href: '#features' },
            { label: 'Pricing', href: '#pricing' },
            { label: 'FAQ', href: '#faq' },
            { label: 'MasterCrab Docs', href: '#docs' },
          ],
        },
        {
          title: 'Company',
          links: [
            { label: 'About Us', href: '#' },
            { label: 'Blog', href: '#' },
            { label: 'Careers', href: '#' },
            { label: 'Contact', href: '#' },
          ],
        },
        {
          title: 'Legal',
          links: [
            { label: 'Imprint', href: '#' },
            { label: 'Privacy Policy', href: '#' },
            { label: 'Terms of Service', href: '#' },
            { label: 'Cookie Policy', href: '#' },
          ],
        },
        {
          title: 'Open Source',
          links: [
            { label: 'MasterCrab (GitHub)', href: 'https://github.com/gdprclaw/mastercrab' },
            { label: 'OpenClaw', href: 'https://github.com/openclaw/openclaw' },
            { label: 'NemoClaw', href: 'https://github.com/nvidia/nemoclaw' },
            { label: 'ClawHub Marketplace', href: 'https://clawhub.ai' },
          ],
        },
      ],
      copyright: '© 2026 GDPRClaw. All rights reserved.',
      madeIn: 'Made in the EU',
      lovesLabel: 'Privacy',
    },
  },

  /* ================================================================
   *  SOC2CLAW — English / SOC 2 Type II framing
   * ================================================================ */
  soc2claw: {
    nav: {
      links: [
        { href: '#problem', label: 'Problem' },
        { href: '#features', label: 'Features' },
        { href: '#how-it-works', label: 'How It Works' },
        { href: '#pricing', label: 'Pricing' },
        { href: '#social-proof', label: 'Customers' },
        { href: '#faq', label: 'FAQ' },
        { href: '#docs', label: 'Docs' },
      ],
      signIn: 'Sign In',
      signUp: 'Sign Up',
    },
    hero: {
      tags: [
        { icon: Shield, label: 'SOC 2 Type II', variant: 'sage' },
        { icon: Lock, label: 'Zero Trust', variant: 'terracotta' },
        { icon: Cpu, label: 'Sandboxed AI', variant: 'cream' },
        { icon: Zap, label: 'NVIDIA-Powered', variant: 'cream' },
      ],
      headlineLines: ['Your AI Employee,', 'secure in the Sandbox.'],
      headlineAccent: 'SOC 2 Type II Compliant.',
      subheadline:
        'AI agents that work inside an <strong>isolated sandbox</strong> – with <strong>52+ skills</strong> for emails, calendar, research and more. <strong>Zero data leakage</strong>, auditor-approved.',
      urgencyText: 'Sandboxed AI is the future of SOC 2-compliant automation.',
      primaryCta: 'Get Started',
      secondaryCta: 'View Pricing',
      stats: [
        { icon: Sparkles, value: '52+', label: 'AI Skills', variant: 'sage', details: ['Email & Calendar', 'Research & Reports', 'Code Review & Docs'] },
        { icon: MessageSquare, value: '22+', label: 'Channels', variant: 'terracotta', details: ['WhatsApp & Telegram', 'Slack & Teams', 'Discord & Signal'] },
        { icon: Clock, value: '24/7', label: 'Availability', variant: 'cream', details: ['Sandbox-protected', 'Audit log active', 'Zero downtime'] },
      ],
    },
    problem: {
      sectionLabel: 'The Challenge',
      headline: 'Manual work is eating your',
      headlineAccent: 'Competitiveness',
      subheadline: 'While your competitors already use AI, you\'re losing time on routine tasks',
      withoutLabel: 'Without AI Employee:',
      withLabel: 'With SOC2Claw:',
      items: [
        {
          icon: Clock,
          title: 'Time Lost',
          metric: '200+',
          subtitle: 'Hours/Month',
          description: 'Manual emails, calendar, reports – time missing for strategic work.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '200+ hours per month on routine tasks',
            '67% of work time is reactive administration',
            'Critical strategic projects get postponed',
            'Overtime and burnout risk increases',
          ],
          pros: [
            'With AI: Inbox Zero in 10 minutes instead of 2 hours',
            'Automatic report generation overnight',
            'Focus on value-creating tasks',
          ],
        },
        {
          icon: AlertTriangle,
          title: 'Compliance Risk',
          metric: '$$$',
          subtitle: 'Audit Failures',
          description: 'AI agents without a sandbox can leak sensitive data. Without proper controls, SOC 2 audits fail and client trust evaporates.',
          variant: 'rose',
          bgVariant: 'terracotta',
          cons: [
            'AI tools without sandbox = uncontrolled data access',
            'Failed SOC 2 audits = lost enterprise clients',
            'Shadow AI usage undermines security posture',
            'No audit trail for AI actions and data access',
            'Breach notification obligations to customers',
            'Reputation loss and contract terminations',
          ],
          pros: [
            'Sandboxed: Landlock + seccomp + network isolation',
            'Complete audit trail for every AI action',
            'Audit-ready for SOC 2 Type II assessors',
          ],
        },
        {
          icon: Users,
          title: 'Talent Shortage',
          metric: '70%',
          subtitle: 'of SMEs',
          description: 'Have no capacity for additional administrative FTEs.',
          variant: 'amber',
          bgVariant: 'sage',
          cons: [
            '70% of companies lack dedicated compliance staff',
            '$100,000+ cost per additional FTE',
            '6+ months until fully operational',
            'High turnover in administrative roles',
            'Difficult to find qualified assistants',
          ],
          pros: [
            'One AI employee with 52+ skills replaces 2–4 FTEs',
            'Ready to work in under 10 minutes',
            'Works 24/7 securely in the sandbox',
            'Scalable without new hires',
          ],
        },
      ],
    },
    features: {
      sectionLabel: 'AI Automation',
      headline: 'One AI employee for',
      headlineAccent: 'all your tasks',
      subheadline: 'Emails, calendar, reports, research – fully automated and SOC 2-secure',
      email: {
        tag: 'Inbox Zero',
        title: 'Email & Communication',
        description: 'AI agents read, categorize and respond to emails automatically – all within the secure sandbox.',
        skillTags: ['himalaya Email Skill', 'Schedule Meetings'],
        checklist: ['Inbox Zero every day', 'Intelligent prioritization', 'Follow-up reminders', 'Multilingual (EN/DE)'],
      },
      research: {
        tag: 'Research',
        title: 'Research & Analysis',
        description: 'Researches market data, summarizes documents and creates professional reports – powered by 52+ OpenClaw Skills.',
        stats: [
          { value: '10x', label: 'faster' },
          { value: '99%', label: 'accuracy' },
        ],
        skillTags: ['summarize Skill', 'coding-agent Skill', '52+ Skills'],
      },
      sandbox: {
        tag: 'NemoClaw',
        title: 'Sandbox Security',
        description: 'Every AI agent runs in an isolated sandbox with Landlock, seccomp and network isolation. No uncontrolled access to your systems.',
        checklist: [
          'Network: All outbound connections blocked',
          'Filesystem: Access only to /sandbox and /tmp',
          'Processes: Privilege escalation prevented',
          'Inference: Only approved AI models allowed',
        ],
      },
      compliance: {
        tag: 'SOC 2',
        title: 'Automatic Compliance',
        description: 'Automatic SOC 2 evidence collection, audit logs and continuous monitoring – without your intervention.',
        checklist: [
          'Continuous control monitoring',
          'Evidence collection automated',
          'Complete audit trail',
          'Auditor-ready reports',
        ],
      },
      integrations: {
        sectionLabel: 'Integrations',
        title: 'Connect with Your Tools',
        subtitle: 'Seamless integration into your existing infrastructure. The AI employee works directly with the tools you use every day.',
        categories: {
          communication: 'Communication Channels',
          productivity: 'Productivity & Documents',
          infrastructure: 'AI & Infrastructure',
        },
      },
    },
    howItWorks: {
      sectionLabel: 'How It Works',
      headline: 'Your AI employee',
      headlineAccent: 'ready in under 10 minutes',
      subheadline: 'From installation to first result – four steps to your secure AI assistant',
      steps: [
        {
          number: '01',
          icon: Download,
          title: 'Install MasterCrab',
          description: 'One command is all it takes. MasterCrab automatically installs NemoClaw, OpenClaw and all dependencies on your server. Docker, sandbox and security policies are configured.',
          variant: 'sage',
          bullets: [
            'One-command install: curl -fsSL install.mastercrab.io | bash',
            'Automatic Docker and sandbox configuration',
            'SOC 2-compliant defaults out of the box',
          ],
          features: ['Ubuntu 22.04+', 'Docker incl.', 'No GPU needed'],
          time: '< 10 min',
        },
        {
          number: '02',
          icon: Settings,
          title: 'Configure Sandbox',
          description: 'Use the local admin panel (localhost) to configure network policies, allowed hosts and AI models. Everything is YAML-based and adjustable at any time.',
          variant: 'terracotta',
          bullets: [
            'Admin Panel: Clean web interface on localhost',
            'Network Policies: Define allowed domains via YAML',
            'AI Models: NVIDIA Nemotron, Ollama or custom models',
          ],
          features: ['YAML Config', 'Hot-Reload', 'Audit Logging'],
          time: '< 5 min',
        },
        {
          number: '03',
          icon: MessageSquare,
          title: 'Connect Channels',
          description: 'Connect your communication channels: WhatsApp, Telegram, Slack, Teams, Discord and more. Your teams communicate directly with the AI employee.',
          variant: 'cream',
          bullets: [
            '22+ channels: WhatsApp, Telegram, Slack, Teams, Discord, Signal',
            'Per-channel allowlists: Only authorized users have access',
            'Group gating: Activated only via @mention in group chats',
          ],
          features: ['22+ Channels', 'Allowlists', 'Encrypted'],
          time: '< 10 min',
        },
        {
          number: '04',
          icon: Sparkles,
          title: 'AI Works in the Sandbox',
          description: 'From now on your AI employee works around the clock – securely contained in the NemoClaw sandbox. 52+ skills for emails, research, reports and more.',
          variant: 'sage',
          bullets: [
            'Sandboxed: Landlock + seccomp + network isolation active',
            '52+ Skills: Email, calendar, research, coding, documents',
            'Complete audit log: Every action is logged',
          ],
          features: ['24/7 Availability', 'SOC 2 Compliance', 'Audit Logs'],
          time: '24/7',
        },
      ],
      ctaText: 'Get Started',
    },
    pricing: {
      sectionLabel: 'Pricing',
      headline: 'Simple, transparent',
      headlineAccent: 'Pricing',
      subheadline: 'Monthly subscription – cancel anytime',
      annualNote: 'Annual billing: 2 months free – cancel anytime',
      plans: [
        {
          title: 'Starter',
          icon: Shield,
          price: '$149',
          priceNote: '/month',
          description: 'For small teams starting with secure AI',
          features: [
            '1 Sandboxed AI Agent',
            'Core Skills: Email, Calendar, Research',
            '3 Communication Channels',
            'Local Sandbox (Landlock + seccomp)',
            'SOC 2 Evidence Collection',
            'Admin Panel (localhost)',
            'Email Support',
            '99.9% Uptime Guarantee',
          ],
          ctaText: 'Buy Now',
          variant: 'default',
          color: 'sage',
        },
        {
          title: 'Professional',
          icon: Sparkles,
          price: '$299',
          priceNote: '/month',
          description: 'Full functionality for growing businesses',
          features: [
            'Up to 5 Sandboxed AI Agents',
            'All 52+ OpenClaw Skills',
            'All 22+ Communication Channels',
            'NVIDIA Nemotron + Ollama Support',
            'Advanced Network Policies (YAML)',
            'ClawHub Marketplace Access',
            'Priority Support (< 2h response)',
            'Team Management & RBAC',
            'Advanced Audit Dashboard',
            'Managed Updates',
          ],
          ctaText: 'Buy Now',
          variant: 'highlighted',
          badge: 'Most Popular',
          color: 'terracotta',
        },
        {
          title: 'Enterprise',
          icon: Building2,
          price: '$599',
          priceNote: '/month',
          description: 'For organizations with highest security requirements',
          features: [
            'Unlimited Sandboxed AI Agents',
            'All Professional Features',
            'Dedicated Account Manager',
            'Custom Skills & Integrations',
            'On-Premise Deployment Support',
            'Premium SLA (99.99% Uptime)',
            'Compliance Manager & Audit Report',
            'On-Site Onboarding & Training',
          ],
          ctaText: 'Buy Now',
          variant: 'default',
          color: 'cream',
        },
      ],
      guaranteeText: '30-day money-back guarantee – risk-free purchase',
    },
    socialProof: {
      sectionLabel: 'Testimonials',
      headline: 'What our',
      headlineAccent: 'customers say',
      subheadline: 'Trusted by over 200 companies worldwide',
      testimonials: [
        {
          quote: 'SOC2Claw completely automated our compliance workflows. The AI agent handles our client emails and creates audit-ready reports – all in the sandbox, zero data leakage.',
          author: 'Dr. Katrin Berger',
          role: 'Chief Compliance Officer',
          company: 'kbht Auditors GmbH',
          rating: 5,
          variant: 'sage',
        },
        {
          quote: 'The sandbox technology was the decisive factor for us. Our firm processes highly sensitive client data – with SOC2Claw we can use AI without compromising our SOC 2 certification.',
          author: 'Stefan Hartmann',
          role: 'Managing Partner',
          company: 'PSP Peters Schönberger & Partner',
          rating: 5,
          variant: 'terracotta',
        },
        {
          quote: 'We augmented 3 administrative positions with the AI employee. Email triage, scheduling and research now run automatically – with 52+ skills we activate as needed.',
          author: 'Lena Richter',
          role: 'Managing Director',
          company: 'Ypsilon GmbH',
          rating: 5,
          variant: 'cream',
        },
      ],
    },
    faq: {
      sectionLabel: 'FAQ',
      headline: 'Frequently Asked',
      headlineAccent: 'Questions',
      subheadline: 'Everything you need to know about SOC2Claw',
      items: [
        {
          question: 'What can the AI employee actually do?',
          answer: 'Your AI employee has 52+ skills: read and respond to emails, manage calendars, conduct research, create reports and presentations, write and review code, summarize documents, and automatically maintain compliance documentation. It works 24/7 within a secure sandbox.',
        },
        {
          question: 'What does "Sandboxed Execution" mean?',
          answer: 'Every AI agent runs in an isolated sandbox, protected by three security layers: Landlock (filesystem isolation – only /sandbox and /tmp accessible), seccomp (blocks dangerous system calls), and network namespaces (all outbound connections blocked by default). Unknown hosts must be approved by the administrator.',
        },
        {
          question: 'Do I need a GPU or special hardware?',
          answer: 'No. AI inference runs via NVIDIA Nemotron 3 Super (120B) in the cloud – you don\'t need a local GPU. For the sandbox you only need a Linux server with Docker: minimum 4 vCPUs, 8 GB RAM (16 GB recommended), and 20-40 GB disk. Alternatively, you can use local models via Ollama.',
        },
        {
          question: 'Is my data really secure?',
          answer: 'Absolutely. Your data never leaves your servers. The AI agent runs in a NemoClaw sandbox with complete network isolation. Only explicitly approved connections are allowed. All actions are logged in a SOC 2-compliant audit log (90-day retention). Sessions are automatically deleted after 30 days.',
        },
        {
          question: 'Which communication channels are supported?',
          answer: 'Over 22 channels: WhatsApp, Telegram, Slack, Microsoft Teams, Discord, Signal, iMessage, Matrix, IRC, Google Chat, WebChat and more. Each channel has its own allowlists – only authorized users can interact with the AI employee. In group chats, the agent is only activated via @mention.',
        },
        {
          question: 'How does this help with SOC 2 compliance?',
          answer: 'SOC2Claw provides continuous control monitoring, automated evidence collection, and complete audit trails for every AI action. The sandboxed architecture ensures data isolation that satisfies SOC 2 Trust Services Criteria. Your auditors get pre-built reports mapped to SOC 2 controls.',
        },
        {
          question: 'How long does setup take?',
          answer: 'Under 10 minutes. One command installs MasterCrab (our NemoClaw wrapper) with all dependencies. Then configure your network policies via the local admin panel and connect your channels. The AI employee starts working immediately.',
        },
      ],
      contactTitle: 'Still have questions?',
      contactSubtitle: 'Our team is happy to help',
      contactCta: 'Contact Us',
    },
    cta: {
      badge: 'Join Now',
      headline: 'Start 2026 with an',
      headlineAccent: 'AI Advantage',
      subheadline: 'Get started with your AI employee now – full functionality, SOC 2-compliant, instantly ready on your servers.',
      emailPlaceholder: 'Your email address',
      submitText: 'Join',
      benefits: ['Ready instantly', 'Cancel anytime', 'SOC 2-compliant'],
      trustBadges: ['SOC 2 Certified', 'Setup in 10 min', '200+ Companies'],
      urgencyText: '2026 will be the year AI becomes standard. The question is no longer "if" but "when".',
    },
    footer: {
      description: 'The secure AI employee for compliance-driven businesses. Sandboxed AI powered by NemoClaw – self-hosted, SOC 2-compliant, no compromises.',
      columns: [
        {
          title: 'Product',
          links: [
            { label: 'Features', href: '#features' },
            { label: 'Pricing', href: '#pricing' },
            { label: 'FAQ', href: '#faq' },
            { label: 'MasterCrab Docs', href: '#docs' },
          ],
        },
        {
          title: 'Company',
          links: [
            { label: 'About Us', href: '#' },
            { label: 'Blog', href: '#' },
            { label: 'Careers', href: '#' },
            { label: 'Contact', href: '#' },
          ],
        },
        {
          title: 'Legal',
          links: [
            { label: 'Imprint', href: '#' },
            { label: 'Privacy Policy', href: '#' },
            { label: 'Terms of Service', href: '#' },
            { label: 'Cookie Policy', href: '#' },
          ],
        },
        {
          title: 'Open Source',
          links: [
            { label: 'MasterCrab (GitHub)', href: 'https://github.com/soc2claw/mastercrab' },
            { label: 'OpenClaw', href: 'https://github.com/openclaw/openclaw' },
            { label: 'NemoClaw', href: 'https://github.com/nvidia/nemoclaw' },
            { label: 'ClawHub Marketplace', href: 'https://clawhub.ai' },
          ],
        },
      ],
      copyright: '© 2026 SOC2Claw. All rights reserved.',
      madeIn: 'SOC 2 Certified',
      lovesLabel: 'Security',
    },
  },
};
